<a href="https://colab.research.google.com/github/Rei2603/KNN/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# KNN_IRIS_1D

In [9]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import neighbors, datasets
import pandas as pd

In [22]:
path = '/content/drive/MyDrive/AI/AIO_Advanced/TEMP/2. KNN/code - update/iris_1D.csv'

data = pd.read_csv(path)
data

Petal_Length  Label
0           1.4    0.0
1           1.0    0.0
2           1.5    0.0
3           3.1    1.0
4           3.8    1.0
5           4.1    1.0

In [34]:
x = data['Petal_Length'].to_numpy()
x = x.reshape(6,1)
y = data['Label'].to_numpy()
print(x,'\n',y)

x_test = [[2.4]]

[[1.4]
 [1. ]
 [1.5]
 [3.1]
 [3.8]
 [4.1]] 
 [0. 0. 0. 1. 1. 1.]


In [35]:
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(x,y)
y_pred = classifier.predict(x_test)
print(y_pred)

[0.]


# KNN_Iris 2D

In [40]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd

In [37]:
path = '/content/drive/MyDrive/AI/AIO_Advanced/TEMP/2. KNN/code - update/iris_2D.csv'
#/content/drive/MyDrive/AI/AIO_Advanced/TEMP/2. KNN/code - update/iris_2D_mm.csv

data = pd.read_csv(path)
data

Petal_Length  Petal_Width  Label
0           1.4          0.2    0.0
1           1.3          0.4    0.0
2           1.4          0.3    0.0
3           4.0          1.0    1.0
4           4.7          1.4    1.0
5           3.6          1.3    1.0

In [49]:
X = data[['Petal_Length', 'Petal_Width']].to_numpy().reshape(6,2)
y = data['Label'].to_numpy()
print(X,'\n',y)

X_test = [[2.6, 0.7]]

[[1.4 0.2]
 [1.3 0.4]
 [1.4 0.3]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]] 
 [0. 0. 0. 1. 1. 1.]


In [51]:
classifier = KNeighborsClassifier(n_neighbors=1)
classifier.fit(X,y)
y_pred = classifier.predict(X_test)
print(y_pred)

[1.]
